# Generated by Django 4.1.3 on 2022-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('niveau', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
